### ISSUE TITLE
require  cloudevents error, cannot load such file -- cloudevents (LoadError)

### ISSUE THREAD

**Issue by ventsing** [cloudevents/sdk-ruby#2]
I try to import ruby cloudevent sdk into my project, and  I have already installed sinatra  and  cloudevents using gem, but unfortunately, it reports require error as following:
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cloudevents (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from rubydownserver.rb:10:in `<main>'

the installed  package is under following 
 root@xxx05422:~/mytest# gem list --local

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundle (0.0.1)
bundler (1.11.2)
cloudevents (0.0.0)
did_you_mean (1.0.0)
httpclient (2.8.3)
io-console (0.4.5)
json (1.8.3)
minitest (5.11.3, 5.8.4)
molinillo (0.4.3)
mustermann (1.0.3)
net-http-persistent (2.9.4)
net-telnet (0.1.1)
power_assert (0.2.7)
psych (2.0.17)
rack (2.0.6)
rack-protection (2.0.5)
rake (12.3.2, 10.5.0)
rdoc (4.2.1)
rubyzip (1.2.2)
sinatra (2.0.5)
soap4r (1.5.8)
test-unit (3.1.7)
thor (0.19.1)
tilt (2.0.9)
zip-zip (0.3)

**Comment by f-mer** [comment]
Hello ventsing 👋 You're getting this error because I wasn't confident enough to cut a release yet. 
If you're adventures enough to try out the current version you can point you're gem directly to the master branch of this repository:

```rb
gem 'cloudevents', git: 'git@github.com:cloudevents/sdk-ruby.git'
```

Just let me know if there is anything else I can help you with to get started 🙂

**Comment by ventsing** [comment]
Thanks for your reply, but I still have problem when I follow the steps as you  advised. 
/root/mytest/vendor/bundle/ruby/2.4.0/bundler/gems/sdk-ruby-d3a145d78a79/lib/cloudevents.rb:1:in `require': cannot load such file -- JSON (LoadError)
        from /root/mytest/vendor/bundle/ruby/2.4.0/bundler/gems/sdk-ruby-d3a145d78a79/lib/cloudevents.rb:1:in `<top (required)>'
I seems JSON lib file can't be loaded in cloudevents.rb.  I  rewrite JSON from uppercase to lowercase, and it works well.

**Comment by dazuma** [comment]
Hi @ventsing, sorry this took so long. We're restarting work on this library now, and have a new implementation in which this issue should no longer be present. We don't have a release yet—that will probably be another week or so for us to get our infrastructure in place. But you can use the master branch. Note that the gem name has changed: it is now `cloud_events`.
