### ISSUE TITLE
to_h does not perform a deep dup leaving the resulting hash partially frozen

### ISSUE THREAD

**Issue by semmons99** [cloudevents/sdk-ruby#43]
When calling `to_h`on an event, if the `data` attribute contains a nested hash, the nested hashes will remain frozen. To fix this we can use `Marshal.load(Marshal.dump(@attributes))` instead of `@attributes.dup`. Alternatively, we could clone `deep_dup` from Rails, though it does miss some edge cases.

I have a PR prepared if you would like me to submit it.

**Comment by dazuma** [comment]
Thanks for the report! I've just been looking at some related fixes, and went ahead and threw this one in.

**Comment by semmons99** [comment]
awesome, thank you.
