### ISSUE TITLE
undefined method `set_encoding' for #<Rack::Lint::InputWrapper> when using config.ru

### ISSUE THREAD

**Issue by joshdemoss** [cloudevents/sdk-ruby#48]
# Issue:
- NoMethodError -- 'set_encoding' for <Rack::Lint::InputWrapper> when using a config.ru file to spin up Sinatra Application for modular or classic using the provided boiler plate on the readme. Works fine when using classic without config.ru

# System info
- Tried rvm 2.7.2 and rvm 3.0.0
- Bundler, sinatra 2.0, cloud_events 2.0
- Catlina

**Comment by dazuma** [comment]
Thanks for the report! We'll get a fix in shortly.
